import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
        paddingTop: '15%',
        backgroundColor: '#eff0f1',
        alignContent: 'center',  
    },
    inputContainer: {
        paddingVertical: '2%',
        borderRadius: 10,
        marginHorizontal: 40,
        marginBottom: '2%',
        paddingHorizontal: 10,
        fontWeight: '500',
    },
    input: {
        backgroundColor: '#d9d9d9',
        paddingVertical: '2%',
        borderRadius: 10,
        marginTop: '2%',
        marginHorizontal: 0,
        marginBottom: '2%',
        paddingHorizontal: 10,
        fontWeight: '500',
    },
    loginLogoImage: {
        maxWidth: '0%',
        maxHeight: '9%',
        marginTop: '10%',
    },
    whiteSheet: {
        width: '100%',
        height: '75%',
        position: 'absolute',
        bottom: 0,
        backgroundColor: '#fff',
        borderTopLeftRadius: 60,
    },
    title: {
        color: '#0364cd',
        textAlign: 'left',
        fontWeight: '800',
        fontSize: 30,
        marginBottom: '3%',
        alignSelf: 'center',
        marginTop: 65,
    },
    backImage: {
        width: '100%',
        height: 340,
        position: 'absolute',
        top: 0,
        resizeMode: 'cover',
    },
    backButtonContainer: {
        alignSelf: 'flex-start',
        marginLeft: '2%',
        borderwidth: 1,
        bordercolor: 'black',
    },
    heading: {
        color: '#ffffff',
        textAlign: 'left',
        fontWeight: '800',
        fontSize: 25,
        paddingRight: '10%',
        paddingTop: '15%',
    },
    componentContainer: {
        width: 250,
        backgroundColor: 'white',
        alignSelf: 'center',
        paddingVertical: 10,
        flexGrow: 1,
    },
    errorText: {

    },
    message: {
        paddingHorizontal: '10%',
        textAlign: 'center',
        marginVertical: 13,
        fontWeight: '400',
    },
    rowContainer: {
        alignItems: 'center',
        width: '100%',
        marginTop: '2%',
    },
    buttonContainer: {
        paddingVertical: '2%',
        marginTop: '2%',
        marginHorizontal: 0,
        paddingHorizontal: 10,
        fontWeight: '500',
    },
    button: {
        backgroundColor: '#053dc4',
        paddingVertical: '2%',
        borderRadius: 50,
        marginTop: '2%',
        marginHorizontal: 0,
        marginBottom: '2%',
        paddingHorizontal: 10,
        fontWeight: '500',
        width: '37%',
        alignSelf: 'center',
    },
    buttonOutlineText: {
        color: '#f1f1f1',
        fontWeight: '500',
        fontSize: 15,
        textAlign: 'center',
    },
    buttonOutline: {
        backgroundColor: '#f1f1f1',
        paddingVertical: '2%',
        borderRadius: 10,
        marginTop: '2%',
        marginHorizontal: 0,
        marginBottom: '2%',
        paddingHorizontal: 10,
        fontWeight: '500',
    },
    headingContainer: {
        color: '#242424',
        textAlign: 'left',
        fontWeight: '800',
        fontSize: 17,
        paddingRight: '10%',
        paddingLeft: '8%',
    },

})